# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#User.first.update(admin:true)
User.third.update(admin:true)
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#Product.find(1).update(category:Category.find(8))
#Product.find(2).update(category:Category.find(6))
#Product.find(3).update(category:Category.find(6))
#Product.find(4).update(category:Category.find(6))
#Product.find(5).update(category:Category.find(7))
#Product.find(6).update(category:Category.find(3))
#Product.find(7).update(category:Category.find(2))
#Product.find(8).update(category:Category.find(2))
#roduct.find(9).update(category:Category.find(5))
#Product.find(10).update(category:Category.find(5))
#roduct.find(11).update(category:Category.find(4))
#roduct.find(12).update(category:Category.find(4))
#Product.find(13).update(category:Category.find(4))
#Product.find(14).update(category:Category.find(8))
#Product.find(15).update(category:Category.find(2))
#Product.find(16).update(category:Category.find(5))
#Product.find(17).update(category:Category.find(3))
#Product.find(18).update(category:Category.find(5))
#Product.find(19).update(category:Category.find(1))
#roduct.find(20).update(category:Category.find(5))
#roduct.find(21).update(category:Category.find(2))
#oduct.find(22).update(category:Category.find(2))
#oduct.find(23).update(category:Category.find(1))
#Product.find(24).update(category:Category.find(2))
#Product.find(25).update(category:Category.find(5))
#Product.find(26).update(category:Category.find(5))
#Product.find(27).update(category:Category.find(8))
#Category.create(name:"sports")
#Category.create(name:"furniture")
#Category.create(name:"clothing")
#Category.create(name:"electronics")
#Category.create(name:"outdoor")
#Category.create(name:"cars")
#Category.create(name:"appliances")
#Category.create(name:"food")
#   Mayor.create(name: 'Emanuel', city: cities.first)
